#!/bin/bash
#
# Copyright 2009 IBM Corp.
# Author: Matt Helsley <matthltc@us.ibm.com>
#
# Sanitize checkpoint/restart kernel headers for userspace.
#

function usage()
{
	echo "Usage: $0 [-h|--help] -s|--kernel-src=DIR"
}

OPTIONS=`getopt -o s:o:h --long kernel-src:,output:,help -- "$@"`
eval set -- "${OPTIONS}"
while true ; do
	case "$1" in
	-s|--kernel-src)
		KERNELSRC="$2"
		shift 2 ;;
	-h|--help)
		usage
		exit 0 ;;
	--)
		shift
		break ;;
	*)
		echo "Unknown option: $1"
		shift
		echo "Unparsed options: $@"
		usage 1>&2
		exit 2 ;;
	esac
done

if [ -z "${KERNELSRC}" -o '!' -d "${KERNELSRC}" ]; then
	usage 1>&2
	exit 2
fi

################################################################################

COND='#if'
set -e
cat - <<-EOFOEOF
/* AUTOMATICALLY GENERATED by rewrite-cr-header.sh */
#ifndef _LINUX_CHECKPOINT_H_
#define _LINUX_CHECKPOINT_H_
#include <asm/unistd.h>
EOFOEOF

#
# Include non-__KERNEL__ sections of include/linux/checkpoint.h using
# cpp to expand only the directives of the kernel header.
#
# The first 6 lines of cpp output write some trashy #define/#undef lines
# we don't want. Would it be better to throw everything away until we see
# "#define _LINUX_CHECKPOINT_H_" ??
#
cpp -CC -P -U__KERNEL__ -undef -nostdinc -fdirectives-only "${KERNELSRC}/include/linux/checkpoint.h" | tail -n '+6'

find "${KERNELSRC}/arch" -name 'unistd*.h' -print | sort | \
while read UNISTDH ; do
	REGEX='[[:space:]]*#[[:space:]]*define[[:space:]]+__NR_(checkpoint|restart)[[:space:]]+[[:digit:]]+'

	[ -z "${UNISTDH}" ] && continue
	KARCH=$(echo "${UNISTDH}" | sed -e 's|.*/arch/\([^/]\+\)/.*|\1|')
	BITNESS=$(basename "${UNISTDH}" | sed -e 's/unistd_*\([12346]\+\)\.h/\1/')

	# Map KARCH to something suitable for CPP e.g. __i386__
	case "${KARCH}" in
	x86)	if [ "${BITNESS}" == "32" ]; then
			CPPARCH=i386
		else
			CPPARCH=x86_64
		fi
		;;
	s390*)	CPPARCH=s390x ;;
	*)	CPPARCH="${KARCH}" ;;
	esac

	grep -q -E "${REGEX}" "${UNISTDH}" || {
		echo '/* '"${CPPARCH}"' unsupported. */'
		continue
	}

	echo -e "${COND} __${CPPARCH}__\\n"
	grep -E "${REGEX}" "${UNISTDH}" | \
	sed -e 's/^[[:space:]]*#define[[:space:]]\+__NR_\([^[:space:]]\+\)[[:space:]]\+\([^[:space:]]\+\).*$/#ifndef __NR_\1\n#define __NR_\1 \2\n#endif\n/'
	COND='#elif'
done
cat - <<-EOFOEOF
#endif /* arch-specific sections */
#endif /* _LINUX_CHECKPOINT_H_ */
EOFOEOF
